import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../../components/NavBar";
import ReduxProvider from "../../provider/ReduxProvider";
import { Toaster } from "react-hot-toast";
import QueryProvider from "../../provider/QueryProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "TodoApp",
  description: "Generated by create solomdev0",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // <QueryProvider>
    <ReduxProvider>
      <html lang="en">
        <body className={`${inter.className} container`}>
          <Navbar />
          {children}
          <Toaster />
        </body>
      </html>
    </ReduxProvider>
    // </QueryProvider>
  );
}
